### ISSUE TITLE
What about prefixes in the plugin names, e.g inspec?

### ISSUE THREAD

**Issue by artem-sidorenko** [chef/chef-oss-practices#225]
Chef InSpec has plugin support and [recognises them](https://github.com/inspec/inspec/blob/e275f3343c0aaa77359666c8bce603619406da32/lib/plugins/inspec-init/lib/inspec-init/cli_plugin.rb#L54) via `inspec|train` prefix in the gem name.

- What should be done with this prefixes in terms of trademarks? 
- If `inspec` prefix can be used, that about [such code](https://github.com/inspec/inspec/blob/e275f3343c0aaa77359666c8bce603619406da32/lib/plugins/inspec-init/lib/inspec-init/cli_plugin.rb#L9), should this be changed to the community constants? Maybe only the part which isn't related to the plugin itself?

cc @cscobie

**Comment by nellshamrell** [comment]
Hi @artem-sidorenko! It's been a bit and I'm refamiliarizing myself with this issue.

Are you asking whether this piece of code https://github.com/inspec/inspec/blob/e275f3343c0aaa77359666c8bce603619406da32/lib/plugins/inspec-init/lib/inspec-init/cli_plugin.rb#L54 needs to be changed to remove the trademark?

Or are you asking whether a community distro can use inspec/train plugins if the plugin gems include inspec in the gem name?

Or both? :)

**Comment by artem-sidorenko** [comment]
@nellshamrell thanks for getting back!

1. question: 'whether this piece of code https://github.com/inspec/inspec/blob/e275f3343c0aaa77359666c8bce603619406da32/lib/plugins/inspec-init/lib/inspec-init/cli_plugin.rb#L54 needs to be changed to remove the trademark?' If yes - this would break the plugin compatibility
2. question: https://github.com/inspec/inspec/blob/e275f3343c0aaa77359666c8bce603619406da32/lib/plugins/inspec-init/lib/inspec-init/cli_plugin.rb#L9, should this code be changed to remove the trademark? It doesn't make any sense if we would keep the plugin compatibility (see question 1)

**Comment by miah** [comment]
cc @chef/inspec-team

**Comment by tas50** [comment]
We decided pretty early on with the trademarks that they would allow the use of the words where necessary in code. That's required for backwards compatibility. Train, inspec, knife, etc are all words necessary for plugin operation and when used for plugin operation that's fine with us.
