### ISSUE TITLE
Adoption of Cookbooks in supermarket requires RFC

### ISSUE THREAD

**Issue by Xorima** [chef/chef-oss-practices#234]
# Describe the problem
As a member of sous-chefs I would like to be able to take ownership of supermarket cookbooks for cookbooks which are clearly not maintained, this was made a part of https://github.com/chef-boneyard/chef-rfc/blob/master/rfc069-cookbook-adoption.md

This process relies on us created an RFC, which is not a valid solution following the deprecation of the RFC process

## Possible Solution
Unsure of a solution, this seems more of a process decision

**Comment by robbkidd** [comment]
🤔

One option is to keep roughly the current ownership transfer process and handle requests as GitHub issues on the Supermarket repo. We can duplicate the RFC process, but as an Issue Template wherein the process can be described to the submitter. Supermarket issues that are cookbook transfer requests could be assumed to be added to the weekly Chef community meeting.

I'll note that the "automatically goes to sous-chef" clause in RFC069 currently depends on an unmaintained cookbook already being marked as up-for-adoption by the cookbook owner. Anyone interested in adopting a cookbook that isn't already up for adoption is expected to make reasonable effort to contact the current owner to offer help with maintenance.

**Comment by bennyvasquez** [comment]
This was completed last year: https://github.com/chef/supermarket/blob/master/docs/cookbookadoptiononsupermarket.md

Working on getting it added to the Supermarket website: https://github.com/chef/supermarket/issues/1884
