### ISSUE TITLE
Chef databag for dynamic path 

### ISSUE THREAD

**Issue by priyanka7340** [chef/chef-oss-practices#304]
I have created a cookbook named Folcpy that does following operation, however the path defined in the code is static but I want it to be dynamic depending on the node it runs
# Cookbook:: Folcpy
# Recipe:: default
#Copyright:: 2020, The Authors, All Rights Reserved.

execute 'Folcpy' do
cwd 'C:\PROD_SERVER'
command 'xcopy /e e:\inetpub\CHEF_APP   C:\PROD_SERVER\PROD /y'
end

execute 'stat' do
cwd 'C:\PROD_SERVER\PROD'
command 'svn status' > c:\Report.txt'
end
---------------------

I have 50 nodes and I have a csv file that has path details of each server in the csv, I think I can use databag and pass the path dynamically 

C:> ~/chef-repo $ mkdir data_bags/operations
C:> ~/chef-repo $ subl data_bags/operations/readfile.json { 
"id": "readfile",
import csv
exampleFile = open('d:\datafile.csv')
fieldnames = ("App_path","Prod_Path","Comp_Path")
exampleReader = csv.reader('d:\datafile.csv', fieldnames)
for row in reader:
 "app":  fieldnames.app_path,
 "prod": fieldnames.prod_path,
 "comp": fieldnames.comp_path
}
Is this correct can I use it like this ?

**Comment by bennyvasquez** [comment]
Hi there! This, unfortunately, is a question that doesn't work here. Please either pose this question in our slack ( https://community-slack.chef.io/ ), or on our discourse ( https://discourse.chef.io/ ).
