### ISSUE TITLE
RTMs not being honored

### ISSUE THREAD

**Issue by bennyvasquez** [chef/chef-oss-practices#334]
As stated here in our [OSS Practices](blob/master/repo-management/repo-states.md#what-is-the-response-time-maximum), each of our repos should have a stated Response Time Maximums for both Issues and Pull Requests. 

Examples can be found on the ones listed below, but it's a widespread problem across a huge number of our repos (eg: outside our primary repos)
https://github.com/chef/mixlib-install/issues
https://github.com/chef/omnibus-toolchain/issues
https://github.com/chef/appbundler/issues
https://github.com/habitat-sh/builder/issues

Unfortunately, for quite some time, these commitments have not been met (even pre-acquisition). We need to assess the viability of these commitments and either ensure we are meeting them, or adjust them for current staffing levels with the expectation that they'll be re-assessed when staffing shifts.

**Comment by kmf** [comment]
I think that the community should atleast help to assist with tagging of the issues, this could help devs decide what to focus on. 

Each repo could have a predefined set of tags people could choose from it could also be helpful if there is predefined severity tags. 

This could make triage easier.

**Comment by damacus** [comment]
Nice idea @kmf. Thankfully we already have a predefined set of labels. #50 tries to address where that isn't the case.

**Comment by Tensibai** [comment]
I'd gladly help to label issues, but I fail to see how that could be done as github permission model doesn't include such an option for non members of an organization.

A kind of bot reading comments to add labels?

**Comment by bennyvasquez** [comment]
Closing this as I'm not active in this project anymore and it doesn't look like this is going to get any attention given the delay thus far.
